-- Create Categories Table
create table categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  icon text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Materials Table
create table materials (
  id bigint generated by default as identity primary key,
  category_id bigint references categories(id),
  title text not null,
  image_url text, -- Supabase Storage URL
  arabic_text text not null,
  translation text not null,
  is_published boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Quizzes Table
create table quizzes (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  thumbnail_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Questions Table
create table questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint references quizzes(id),
  question_text text not null,
  image_url text,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_answer text not null, -- 'a', 'b', 'c', or 'd'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS)
-- For now, enable read access for everyone, and write access only for authenticated users (admins)

alter table categories enable row level security;
alter table materials enable row level security;
alter table quizzes enable row level security;
alter table questions enable row level security;

-- Policies for Categories
create policy "Public categories are viewable by everyone." on categories for select using (true);
create policy "Admins can insert categories." on categories for insert with check (auth.role() = 'authenticated');
create policy "Admins can update categories." on categories for update using (auth.role() = 'authenticated');
create policy "Admins can delete categories." on categories for delete using (auth.role() = 'authenticated');

-- Policies for Materials
create policy "Public materials are viewable by everyone." on materials for select using (true);
create policy "Admins can insert materials." on materials for insert with check (auth.role() = 'authenticated');
create policy "Admins can update materials." on materials for update using (auth.role() = 'authenticated');
create policy "Admins can delete materials." on materials for delete using (auth.role() = 'authenticated');

-- Policies for Quizzes
create policy "Public quizzes are viewable by everyone." on quizzes for select using (true);
create policy "Admins can insert quizzes." on quizzes for insert with check (auth.role() = 'authenticated');
create policy "Admins can update quizzes." on quizzes for update using (auth.role() = 'authenticated');
create policy "Admins can delete quizzes." on quizzes for delete using (auth.role() = 'authenticated');

-- Policies for Questions
create policy "Public questions are viewable by everyone." on questions for select using (true);
create policy "Admins can insert questions." on questions for insert with check (auth.role() = 'authenticated');
create policy "Admins can update questions." on questions for update using (auth.role() = 'authenticated');
create policy "Admins can delete questions." on questions for delete using (auth.role() = 'authenticated');

-- Storage Buckets (You need to create these in the Supabase Dashboard > Storage)
-- Bucket name: 'images'
-- Enable Public Access
